language: node_js
node_js:
  - "0.11"
  - "0.10"
before_install: npm install -g grunt-cli
install:
  - sudo npm install -g grunt-cli
  - sudo npm install -g bower
  - sudo npm install
before_script:
  - bower install
script:
  - grunt dist