# Site settings
title: jQuery Progress Timer
email: tnorberg@thomasnorberg.com
description: > # this means to ignore newlines until "baseurl:"
  The jQuery bootstrap progress timer did not work quite the way that I wanted so I extended its capabilities
baseurl: "http://tnory56.github.io/jquery-progressTimer" # the subpath of your site, e.g. /blog/
url: "http://tnory56.github.io/" # the base hostname & protocol for your site
twitter_username: tommyguns66
github_username:  tnory56

# Build settings
markdown: kramdown
highlighter: pygments.rb

#gems:
 # - rouge